### ISSUE TITLE
Add organizations

### ISSUE THREAD

**Issue by JohannesRudolph** [Lawiss/tap-zammad#11]
Super cool tap, played around with it and it worked great!

Can you add support for the organizations stream? https://docs.zammad.org/en/latest/api/organization.html

**Comment by Lawiss** [comment]
Hello Johannes,
Thanks for the feedback! The tap is still experimental so for the moment I only added the streams that I needed on my use case. I'll open a PR to add the organization stream to.

**Comment by Lawiss** [comment]
I released v0.0.3 with the addition of Organizations stream, you should be able to install it from pypi.
