### ISSUE TITLE
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'

### ISSUE THREAD

**Issue by pnadolny13** [Lawiss/tap-zammad#19]
I'm using python 3.9 which looks like its [supported in the pyproject.toml](https://github.com/Lawiss/tap-zammad/blob/65492066c77f5b5e94fd7bfb206b25d223dc0bf7/pyproject.toml#L13) but I think the pipe union syntax requires 3.10 or newer so its raising an error.

```
tap_zammad/paginators.py", line 33, in ZammadAPIPaginator
    def get_next_url_params(self, response: Response) -> dict | None:
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'
```

I guess the options are:
- use something like `Optional[dict]` or `Union[dict, None]`
- Or be more restrictive on python version >=3.10 (less ideal)

**Comment by Lawiss** [comment]
Hello @pnadolny13,

You are right, I tried to keep my typing syntax backwards compatible but I missed this one. I agree with`Optional[dict]`, I'll commit a fix.

**Comment by pnadolny13** [comment]
@Lawiss awesome, thanks!

**Comment by Lawiss** [comment]
It should work now!
